---
server:
  httpListenAddr: ":8080"
storage:
  driver: "disk" # Valid values are "disk" or "git"
  disk: # Only required if "driver" is "disk"
    directory: /policies
    watchForChanges: false
auxData:
  jwt:
    keySets:
      - id: ks1
        local:
          file: /keys/verify_key.jwk
schema:
  enforcement: reject
